export const SUB_NAV_ACTIONS ={
    CHANGE_TAB : "CHANGE_TAB"
}

export const PRODUCT_ACTIONS = {
    GET_PRODUCTS : "GET_PRODUCTS",
    PRODUCT_LOADING : "PRODUCT_LOADING",
    PRODUCT_LOADING_DONE : "PRODUCT_LOADING_DONE"
}

export const CATEGORY_ACTIONS = {
    GET_CATEGORY : "GET_CATEGORY",
    CATEGORY_LOADING : "CATEGORY_LOADING",
    CATEGORY_LOADING_DONE : "CATEGORY_LOADING_DONE"
}


export const CAMPAIGN_ACTIONS = {
    GET_CAMPAIGN : "GET_CAMPAIGN",
    CAMPAIGN_LOADING : "CAMPAIGN_LOADING",
    CAMPAIGN_LOADING_DONE : "CAMPAIGN_LOADING_DONE"
}

export const SALE_ACTIONS = {
    GET_SALE : "GET_SALE",
    SALE_LOADING : "SALE_LOADING",
    SALE_LOADING_DONE : "SALE_LOADING_DONE"
}

export const CART_ACTIONS = {
    ADD_CART : "ADD_CART",
    REMOVE_CART : "REMOVE_CART",
    DECREMENT_CART : "DECREMENT_CART",
    INCREMENT_CART : "INCREMENT_CART",
    CLEAR_CART : "CLEAR_CART",
    
}