export const SUB_NAV_ACTIONS ={
    CHANGE_TAB : "CHANGE_TAB"
}

export const PRODUCT_ACTIONS = {
    GET_PRODUCTS : "GET_PRODUCTS",
    PRODUCT_LOADING : "PRODUCT_LOADING",
    PRODUCT_LOADING_DONE : "PRODUCT_LOADING_DONE"
}

export const CATEGORY_ACTIONS = {
    GET_CATEGORY : "GET_CATEGORY",
    CATEGORY_LOADING : "CATEGORY_LOADING",
    CATEGORY_LOADING_DONE : "CATEGORY_LOADING_DONE"
}